Kyklydse\ChristmasListBundle\Entity\User:
    type: entity
    repositoryClass: Kyklydse\ChristmasListBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        facebookId:
            type: string
            nullable: true
            unique: true
    manyToMany:
        friends:
            targetEntity: User
            joinTable:
                name: user_friends
                inverseJoinColumns:
                    friend_id:
                        referenceColumnName: id
