Kyklydse\ChristmasListBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        facebookId:
            type: string
            nullable: true
            unique: true
