applications:
    php-server:
        type: custom
        template: docker/php-server/Dockerfile
        links: [mongodb]
        ports:
            8000: 8000
        volumes:
            .: /var/www
    mongodb:
        type: index
        image: mongo
        volumes:
            ./app/var/mongo: /data/db

binaries:
    php:
        type: custom
        template: docker/php-cli/Dockerfile
