imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:          ~
    default_locale:  %locale%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%

doctrine:
    dbal:
        driver: pdo_mysql
        host: "%db.host%"
        user: "%db.user%"
        password: "%db.password%"
        dbname: "%db.name%"
    orm:
        mappings:
            FOSUserBundle: ~
            KyklydseChristmasListBundle: ~
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kyklydse\ChristmasListBundle\Entity\User
    from_email:
        address: postmaster@kyklydse.com
        sender_name: Christmas Lists
