KyklydseChristmasListBundle:
    resource: "@KyklydseChristmasListBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

facebook_redirect:
    pattern: /login/facebook
    defaults:
        _controller: KyklydseChristmasListBundle:Facebook:redirect

facebook_callback:
    pattern: /login/check-facebook
    defaults:
        _controller: KyklydseChristmasListBundle:Facebook:callback

user_profile:
    pattern: /profile
    defaults:
        _controller: KyklydseChristmasListBundle:User:profile

user_friends_friends:
    pattern: /profile/friendsfriends
    defaults:
        _controller: KyklydseChristmasListBundle:User:inviteFriendsFriends
